spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  data:
    mongodb:
      local:
        uri: mongodb://localhost:30001/LabMedicoes
        database: LabMedicoes
        collections:
          raw-data: rawdata
          readings-processor-timestamp-holder: readinsProcessorTimestampHolder
          sensor-manufactured-info: cloudSQLBackupSensor
    mysql-pc2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307
      password: 'password'
      pool-size: 30
      username: root

broker:
  uri: "tcp://broker.mqtt-dashboard.com:1883"
  topic1: "readings-grupo11"
  topic2: "anomalies-grupo11"
  topic3: "wrong-format-payload-grupo11"

datatype:
  anomaly: "anomalia"
  measurement: "medicao"
  unprocessable: "unprocessableEntity"

server:
  error:
    include-binding-errors: always
    include-message: always