spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  data:
    mongodb:
      local:
        uri: mongodb://localhost:30002/LabMedicoes
        database: LabMedicoes
        collections:
          filtered-data: filteredData
          readings-processor-timestamp-holder: readinsProcessorTimestampHolder
    mysql-pc2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307
      password: 'password'
      pool-size: 30
      username: software

broker:
  uri: "tcp://broker.mqtt-dashboard.com:1883"
  topic1: "readings"
  topic2: "anomalies"

server:
  error:
    include-binding-errors: always
    include-message: always