spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  data:
    mongodb:
      local:
        uri: mongodb://mongo1,mongo2,mongo3/?replicaSet=dbrs
        database: LabMedicoes
        collections:
          raw-data: rawdata
          sensors-without-manufacture-info: sensorWithoutManufactureInfo
          readings-processor-timestamp-holder: readinsProcessorTimestampHolder
          no-manufacture-sensor-timestamp-holder: noManufactureSensorTimestampHolder
          sensor-manufactured-info: cloudSQLBackupSensor
    mysql-pc2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/localsensor?jdbcCompliantTruncation=false
      password: 'password'
      pool-size: 30
      username: root

broker:
  uri: "tcp://broker.mqtt-dashboard.com:1883"
  topic1: "readings-grupo11"
  topic2: "anomalies-grupo11"
  topic3: "wrong-format-payload-grupo11"

datatype:
  anomaly: "anomalia"
  measurement: "medicao"
  unprocessable: "unprocessableEntity"

server:
  error:
    include-binding-errors: always
    include-message: always

application-logic:
  ema-parameters:
    alphas:
      temperature: 0.6
      humidity: 0.5
      luminosity: 0.5
    peak-detection-thresholds:
      temperature: 0.1
      humidity: 0.3
      luminosity: 1
    peak-detection-anomaly-counter-trigger:
      temperature: 4
      humidity: 3
      luminosity: 3
