spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  data:
    mongodb:
      local:
        uri: mongodb://localhost:30002/LabMedicoes
        database: LabMedicoes
        collections:
          filtered-data: filteredData

server:
  error:
    include-binding-errors: always
    include-message: always