spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  data:
    mongodb:
      local:
        uri: mongodb://localhost:30001/LabMedicoes
        database: LabMedicoes
        collections:
          rawdata: rawdata
          cloudsql-backup-sensor: cloudSQLBackupSensor
          cloudsql-backup-zone: cloudSQLBackupZone
      cloud:
        uri: mongodb://aluno:aluno@194.210.86.10:27017/sid2022?authSource=admin
        database: sid2022
        collection: medicoes2022



  datasource:
    mysql-cloud:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://194.210.86.10:3306/sid2022
      password: 'aluno'
      pool-size: 30
      username: aluno

server:
  error:
    include-binding-errors: always
    include-message: always